# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class StockPrice(models.Model):
    # index = models.BigIntegerField(blank=True, null=True)
    date = models.DateTimeField(db_column='date', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    adm = models.FloatField(db_column='ADM', blank=True, null=True)  # Field name made lowercase.
    adp = models.FloatField(db_column='ADP', blank=True, null=True)  # Field name made lowercase.
    adsk = models.FloatField(db_column='ADSK', blank=True, null=True)  # Field name made lowercase.
    aee = models.FloatField(db_column='AEE', blank=True, null=True)  # Field name made lowercase.
    aep = models.FloatField(db_column='AEP', blank=True, null=True)  # Field name made lowercase.
    aes = models.FloatField(db_column='AES', blank=True, null=True)  # Field name made lowercase.
    afl = models.FloatField(db_column='AFL', blank=True, null=True)  # Field name made lowercase.
    aig = models.FloatField(db_column='AIG', blank=True, null=True)  # Field name made lowercase.
    aiz = models.FloatField(db_column='AIZ', blank=True, null=True)  # Field name made lowercase.
    ajg = models.FloatField(db_column='AJG', blank=True, null=True)  # Field name made lowercase.
    akam = models.FloatField(db_column='AKAM', blank=True, null=True)  # Field name made lowercase.
    alb = models.FloatField(db_column='ALB', blank=True, null=True)  # Field name made lowercase.
    algn = models.FloatField(db_column='ALGN', blank=True, null=True)  # Field name made lowercase.
    alk = models.FloatField(db_column='ALK', blank=True, null=True)  # Field name made lowercase.
    all = models.FloatField(db_column='ALL', blank=True, null=True)  # Field name made lowercase.
    alle = models.FloatField(db_column='ALLE', blank=True, null=True)  # Field name made lowercase.
    alxn = models.FloatField(db_column='ALXN', blank=True, null=True)  # Field name made lowercase.
    amat = models.FloatField(db_column='AMAT', blank=True, null=True)  # Field name made lowercase.
    amcr = models.FloatField(db_column='AMCR', blank=True, null=True)  # Field name made lowercase.
    amd = models.FloatField(db_column='AMD', blank=True, null=True)  # Field name made lowercase.
    ame = models.FloatField(db_column='AME', blank=True, null=True)  # Field name made lowercase.
    amgn = models.FloatField(db_column='AMGN', blank=True, null=True)  # Field name made lowercase.
    amp = models.FloatField(db_column='AMP', blank=True, null=True)  # Field name made lowercase.
    amt = models.FloatField(db_column='AMT', blank=True, null=True)  # Field name made lowercase.
    amzn = models.FloatField(db_column='AMZN', blank=True, null=True)  # Field name made lowercase.
    anet = models.FloatField(db_column='ANET', blank=True, null=True)  # Field name made lowercase.
    anss = models.FloatField(db_column='ANSS', blank=True, null=True)  # Field name made lowercase.
    antm = models.FloatField(db_column='ANTM', blank=True, null=True)  # Field name made lowercase.
    aon = models.FloatField(db_column='AON', blank=True, null=True)  # Field name made lowercase.
    aos = models.FloatField(db_column='AOS', blank=True, null=True)  # Field name made lowercase.
    apa = models.FloatField(db_column='APA', blank=True, null=True)  # Field name made lowercase.
    apd = models.FloatField(db_column='APD', blank=True, null=True)  # Field name made lowercase.
    aph = models.FloatField(db_column='APH', blank=True, null=True)  # Field name made lowercase.
    aptv = models.FloatField(db_column='APTV', blank=True, null=True)  # Field name made lowercase.
    are = models.FloatField(db_column='ARE', blank=True, null=True)  # Field name made lowercase.
    ato = models.FloatField(db_column='ATO', blank=True, null=True)  # Field name made lowercase.
    atvi = models.FloatField(db_column='ATVI', blank=True, null=True)  # Field name made lowercase.
    avb = models.FloatField(db_column='AVB', blank=True, null=True)  # Field name made lowercase.
    avgo = models.FloatField(db_column='AVGO', blank=True, null=True)  # Field name made lowercase.
    avy = models.FloatField(db_column='AVY', blank=True, null=True)  # Field name made lowercase.
    awk = models.FloatField(db_column='AWK', blank=True, null=True)  # Field name made lowercase.
    axp = models.FloatField(db_column='AXP', blank=True, null=True)  # Field name made lowercase.
    azo = models.FloatField(db_column='AZO', blank=True, null=True)  # Field name made lowercase.
    ba = models.FloatField(db_column='BA', blank=True, null=True)  # Field name made lowercase.
    bac = models.FloatField(db_column='BAC', blank=True, null=True)  # Field name made lowercase.
    bax = models.FloatField(db_column='BAX', blank=True, null=True)  # Field name made lowercase.
    bby = models.FloatField(db_column='BBY', blank=True, null=True)  # Field name made lowercase.
    bdx = models.FloatField(db_column='BDX', blank=True, null=True)  # Field name made lowercase.
    ben = models.FloatField(db_column='BEN', blank=True, null=True)  # Field name made lowercase.
    biib = models.FloatField(db_column='BIIB', blank=True, null=True)  # Field name made lowercase.
    bio = models.FloatField(db_column='BIO', blank=True, null=True)  # Field name made lowercase.
    bk = models.FloatField(db_column='BK', blank=True, null=True)  # Field name made lowercase.
    bkng = models.FloatField(db_column='BKNG', blank=True, null=True)  # Field name made lowercase.
    bkr = models.FloatField(db_column='BKR', blank=True, null=True)  # Field name made lowercase.
    blk = models.FloatField(db_column='BLK', blank=True, null=True)  # Field name made lowercase.
    bll = models.FloatField(db_column='BLL', blank=True, null=True)  # Field name made lowercase.
    bmy = models.FloatField(db_column='BMY', blank=True, null=True)  # Field name made lowercase.
    br = models.FloatField(db_column='BR', blank=True, null=True)  # Field name made lowercase.
    bsx = models.FloatField(db_column='BSX', blank=True, null=True)  # Field name made lowercase.
    bwa = models.FloatField(db_column='BWA', blank=True, null=True)  # Field name made lowercase.
    bxp = models.FloatField(db_column='BXP', blank=True, null=True)  # Field name made lowercase.
    c = models.FloatField(db_column='C', blank=True, null=True)  # Field name made lowercase.
    cag = models.FloatField(db_column='CAG', blank=True, null=True)  # Field name made lowercase.
    cah = models.FloatField(db_column='CAH', blank=True, null=True)  # Field name made lowercase.
    carr = models.FloatField(db_column='CARR', blank=True, null=True)  # Field name made lowercase.
    cat = models.FloatField(db_column='CAT', blank=True, null=True)  # Field name made lowercase.
    cb = models.FloatField(db_column='CB', blank=True, null=True)  # Field name made lowercase.
    cboe = models.FloatField(db_column='CBOE', blank=True, null=True)  # Field name made lowercase.
    cbre = models.FloatField(db_column='CBRE', blank=True, null=True)  # Field name made lowercase.
    cci = models.FloatField(db_column='CCI', blank=True, null=True)  # Field name made lowercase.
    ccl = models.FloatField(db_column='CCL', blank=True, null=True)  # Field name made lowercase.
    cdns = models.FloatField(db_column='CDNS', blank=True, null=True)  # Field name made lowercase.
    cdw = models.FloatField(db_column='CDW', blank=True, null=True)  # Field name made lowercase.
    ce = models.FloatField(db_column='CE', blank=True, null=True)  # Field name made lowercase.
    cern = models.FloatField(db_column='CERN', blank=True, null=True)  # Field name made lowercase.
    cf = models.FloatField(db_column='CF', blank=True, null=True)  # Field name made lowercase.
    cfg = models.FloatField(db_column='CFG', blank=True, null=True)  # Field name made lowercase.
    chd = models.FloatField(db_column='CHD', blank=True, null=True)  # Field name made lowercase.
    chrw = models.FloatField(db_column='CHRW', blank=True, null=True)  # Field name made lowercase.
    chtr = models.FloatField(db_column='CHTR', blank=True, null=True)  # Field name made lowercase.
    ci = models.FloatField(db_column='CI', blank=True, null=True)  # Field name made lowercase.
    cinf = models.FloatField(db_column='CINF', blank=True, null=True)  # Field name made lowercase.
    cl = models.FloatField(db_column='CL', blank=True, null=True)  # Field name made lowercase.
    clx = models.FloatField(db_column='CLX', blank=True, null=True)  # Field name made lowercase.
    cma = models.FloatField(db_column='CMA', blank=True, null=True)  # Field name made lowercase.
    cmcsa = models.FloatField(db_column='CMCSA', blank=True, null=True)  # Field name made lowercase.
    cme = models.FloatField(db_column='CME', blank=True, null=True)  # Field name made lowercase.
    cmg = models.FloatField(db_column='CMG', blank=True, null=True)  # Field name made lowercase.
    cmi = models.FloatField(db_column='CMI', blank=True, null=True)  # Field name made lowercase.
    cms = models.FloatField(db_column='CMS', blank=True, null=True)  # Field name made lowercase.
    cnc = models.FloatField(db_column='CNC', blank=True, null=True)  # Field name made lowercase.
    cnp = models.FloatField(db_column='CNP', blank=True, null=True)  # Field name made lowercase.
    cof = models.FloatField(db_column='COF', blank=True, null=True)  # Field name made lowercase.
    cog = models.FloatField(db_column='COG', blank=True, null=True)  # Field name made lowercase.
    coo = models.FloatField(db_column='COO', blank=True, null=True)  # Field name made lowercase.
    cop = models.FloatField(db_column='COP', blank=True, null=True)  # Field name made lowercase.
    cost = models.FloatField(db_column='COST', blank=True, null=True)  # Field name made lowercase.
    cpb = models.FloatField(db_column='CPB', blank=True, null=True)  # Field name made lowercase.
    cprt = models.FloatField(db_column='CPRT', blank=True, null=True)  # Field name made lowercase.
    crm = models.FloatField(db_column='CRM', blank=True, null=True)  # Field name made lowercase.
    csco = models.FloatField(db_column='CSCO', blank=True, null=True)  # Field name made lowercase.
    csx = models.FloatField(db_column='CSX', blank=True, null=True)  # Field name made lowercase.
    ctas = models.FloatField(db_column='CTAS', blank=True, null=True)  # Field name made lowercase.
    ctlt = models.FloatField(db_column='CTLT', blank=True, null=True)  # Field name made lowercase.
    ctsh = models.FloatField(db_column='CTSH', blank=True, null=True)  # Field name made lowercase.
    ctva = models.FloatField(db_column='CTVA', blank=True, null=True)  # Field name made lowercase.
    ctxs = models.FloatField(db_column='CTXS', blank=True, null=True)  # Field name made lowercase.
    cvs = models.FloatField(db_column='CVS', blank=True, null=True)  # Field name made lowercase.
    cvx = models.FloatField(db_column='CVX', blank=True, null=True)  # Field name made lowercase.
    czr = models.FloatField(db_column='CZR', blank=True, null=True)  # Field name made lowercase.
    d = models.FloatField(db_column='D', blank=True, null=True)  # Field name made lowercase.
    dal = models.FloatField(db_column='DAL', blank=True, null=True)  # Field name made lowercase.
    dd = models.FloatField(db_column='DD', blank=True, null=True)  # Field name made lowercase.
    de = models.FloatField(db_column='DE', blank=True, null=True)  # Field name made lowercase.
    dfs = models.FloatField(db_column='DFS', blank=True, null=True)  # Field name made lowercase.
    dg = models.FloatField(db_column='DG', blank=True, null=True)  # Field name made lowercase.
    dgx = models.FloatField(db_column='DGX', blank=True, null=True)  # Field name made lowercase.
    dhi = models.FloatField(db_column='DHI', blank=True, null=True)  # Field name made lowercase.
    dhr = models.FloatField(db_column='DHR', blank=True, null=True)  # Field name made lowercase.
    dis = models.FloatField(db_column='DIS', blank=True, null=True)  # Field name made lowercase.
    disca = models.FloatField(db_column='DISCA', blank=True, null=True)  # Field name made lowercase.
    disck = models.FloatField(db_column='DISCK', blank=True, null=True)  # Field name made lowercase.
    dish = models.FloatField(db_column='DISH', blank=True, null=True)  # Field name made lowercase.
    dlr = models.FloatField(db_column='DLR', blank=True, null=True)  # Field name made lowercase.
    dltr = models.FloatField(db_column='DLTR', blank=True, null=True)  # Field name made lowercase.
    dov = models.FloatField(db_column='DOV', blank=True, null=True)  # Field name made lowercase.
    dow = models.FloatField(db_column='DOW', blank=True, null=True)  # Field name made lowercase.
    dpz = models.FloatField(db_column='DPZ', blank=True, null=True)  # Field name made lowercase.
    dre = models.FloatField(db_column='DRE', blank=True, null=True)  # Field name made lowercase.
    dri = models.FloatField(db_column='DRI', blank=True, null=True)  # Field name made lowercase.
    dte = models.FloatField(db_column='DTE', blank=True, null=True)  # Field name made lowercase.
    duk = models.FloatField(db_column='DUK', blank=True, null=True)  # Field name made lowercase.
    dva = models.FloatField(db_column='DVA', blank=True, null=True)  # Field name made lowercase.
    dvn = models.FloatField(db_column='DVN', blank=True, null=True)  # Field name made lowercase.
    dxc = models.FloatField(db_column='DXC', blank=True, null=True)  # Field name made lowercase.
    dxcm = models.FloatField(db_column='DXCM', blank=True, null=True)  # Field name made lowercase.
    ea = models.FloatField(db_column='EA', blank=True, null=True)  # Field name made lowercase.
    ebay = models.FloatField(db_column='EBAY', blank=True, null=True)  # Field name made lowercase.
    ecl = models.FloatField(db_column='ECL', blank=True, null=True)  # Field name made lowercase.
    ed = models.FloatField(db_column='ED', blank=True, null=True)  # Field name made lowercase.
    efx = models.FloatField(db_column='EFX', blank=True, null=True)  # Field name made lowercase.
    eix = models.FloatField(db_column='EIX', blank=True, null=True)  # Field name made lowercase.
    el = models.FloatField(db_column='EL', blank=True, null=True)  # Field name made lowercase.
    emn = models.FloatField(db_column='EMN', blank=True, null=True)  # Field name made lowercase.
    emr = models.FloatField(db_column='EMR', blank=True, null=True)  # Field name made lowercase.
    enph = models.FloatField(db_column='ENPH', blank=True, null=True)  # Field name made lowercase.
    eog = models.FloatField(db_column='EOG', blank=True, null=True)  # Field name made lowercase.
    eqix = models.FloatField(db_column='EQIX', blank=True, null=True)  # Field name made lowercase.
    eqr = models.FloatField(db_column='EQR', blank=True, null=True)  # Field name made lowercase.
    es = models.FloatField(db_column='ES', blank=True, null=True)  # Field name made lowercase.
    ess = models.FloatField(db_column='ESS', blank=True, null=True)  # Field name made lowercase.
    etn = models.FloatField(db_column='ETN', blank=True, null=True)  # Field name made lowercase.
    etr = models.FloatField(db_column='ETR', blank=True, null=True)  # Field name made lowercase.
    etsy = models.FloatField(db_column='ETSY', blank=True, null=True)  # Field name made lowercase.
    evrg = models.FloatField(db_column='EVRG', blank=True, null=True)  # Field name made lowercase.
    ew = models.FloatField(db_column='EW', blank=True, null=True)  # Field name made lowercase.
    exc = models.FloatField(db_column='EXC', blank=True, null=True)  # Field name made lowercase.
    expd = models.FloatField(db_column='EXPD', blank=True, null=True)  # Field name made lowercase.
    expe = models.FloatField(db_column='EXPE', blank=True, null=True)  # Field name made lowercase.
    exr = models.FloatField(db_column='EXR', blank=True, null=True)  # Field name made lowercase.
    f = models.FloatField(db_column='F', blank=True, null=True)  # Field name made lowercase.
    fang = models.FloatField(db_column='FANG', blank=True, null=True)  # Field name made lowercase.
    fast = models.FloatField(db_column='FAST', blank=True, null=True)  # Field name made lowercase.
    fb = models.FloatField(db_column='FB', blank=True, null=True)  # Field name made lowercase.
    fbhs = models.FloatField(db_column='FBHS', blank=True, null=True)  # Field name made lowercase.
    fcx = models.FloatField(db_column='FCX', blank=True, null=True)  # Field name made lowercase.
    fdx = models.FloatField(db_column='FDX', blank=True, null=True)  # Field name made lowercase.
    fe = models.FloatField(db_column='FE', blank=True, null=True)  # Field name made lowercase.
    ffiv = models.FloatField(db_column='FFIV', blank=True, null=True)  # Field name made lowercase.
    fis = models.FloatField(db_column='FIS', blank=True, null=True)  # Field name made lowercase.
    fisv = models.FloatField(db_column='FISV', blank=True, null=True)  # Field name made lowercase.
    fitb = models.FloatField(db_column='FITB', blank=True, null=True)  # Field name made lowercase.
    flir = models.FloatField(db_column='FLIR', blank=True, null=True)  # Field name made lowercase.
    flt = models.FloatField(db_column='FLT', blank=True, null=True)  # Field name made lowercase.
    fmc = models.FloatField(db_column='FMC', blank=True, null=True)  # Field name made lowercase.
    fox = models.FloatField(db_column='FOX', blank=True, null=True)  # Field name made lowercase.
    foxa = models.FloatField(db_column='FOXA', blank=True, null=True)  # Field name made lowercase.
    frc = models.FloatField(db_column='FRC', blank=True, null=True)  # Field name made lowercase.
    frt = models.FloatField(db_column='FRT', blank=True, null=True)  # Field name made lowercase.
    ftnt = models.FloatField(db_column='FTNT', blank=True, null=True)  # Field name made lowercase.
    ftv = models.FloatField(db_column='FTV', blank=True, null=True)  # Field name made lowercase.
    gd = models.FloatField(db_column='GD', blank=True, null=True)  # Field name made lowercase.
    ge = models.FloatField(db_column='GE', blank=True, null=True)  # Field name made lowercase.
    gild = models.FloatField(db_column='GILD', blank=True, null=True)  # Field name made lowercase.
    gis = models.FloatField(db_column='GIS', blank=True, null=True)  # Field name made lowercase.
    gl = models.FloatField(db_column='GL', blank=True, null=True)  # Field name made lowercase.
    glw = models.FloatField(db_column='GLW', blank=True, null=True)  # Field name made lowercase.
    gm = models.FloatField(db_column='GM', blank=True, null=True)  # Field name made lowercase.
    gnrc = models.FloatField(db_column='GNRC', blank=True, null=True)  # Field name made lowercase.
    goog = models.FloatField(db_column='GOOG', blank=True, null=True)  # Field name made lowercase.
    googl = models.FloatField(db_column='GOOGL', blank=True, null=True)  # Field name made lowercase.
    gpc = models.FloatField(db_column='GPC', blank=True, null=True)  # Field name made lowercase.
    gpn = models.FloatField(db_column='GPN', blank=True, null=True)  # Field name made lowercase.
    gps = models.FloatField(db_column='GPS', blank=True, null=True)  # Field name made lowercase.
    grmn = models.FloatField(db_column='GRMN', blank=True, null=True)  # Field name made lowercase.
    gs = models.FloatField(db_column='GS', blank=True, null=True)  # Field name made lowercase.
    gww = models.FloatField(db_column='GWW', blank=True, null=True)  # Field name made lowercase.
    hal = models.FloatField(db_column='HAL', blank=True, null=True)  # Field name made lowercase.
    has = models.FloatField(db_column='HAS', blank=True, null=True)  # Field name made lowercase.
    hban = models.FloatField(db_column='HBAN', blank=True, null=True)  # Field name made lowercase.
    hbi = models.FloatField(db_column='HBI', blank=True, null=True)  # Field name made lowercase.
    hca = models.FloatField(db_column='HCA', blank=True, null=True)  # Field name made lowercase.
    hd = models.FloatField(db_column='HD', blank=True, null=True)  # Field name made lowercase.
    hes = models.FloatField(db_column='HES', blank=True, null=True)  # Field name made lowercase.
    hfc = models.FloatField(db_column='HFC', blank=True, null=True)  # Field name made lowercase.
    hig = models.FloatField(db_column='HIG', blank=True, null=True)  # Field name made lowercase.
    hii = models.FloatField(db_column='HII', blank=True, null=True)  # Field name made lowercase.
    hlt = models.FloatField(db_column='HLT', blank=True, null=True)  # Field name made lowercase.
    holx = models.FloatField(db_column='HOLX', blank=True, null=True)  # Field name made lowercase.
    hon = models.FloatField(db_column='HON', blank=True, null=True)  # Field name made lowercase.
    hpe = models.FloatField(db_column='HPE', blank=True, null=True)  # Field name made lowercase.
    hpq = models.FloatField(db_column='HPQ', blank=True, null=True)  # Field name made lowercase.
    hrl = models.FloatField(db_column='HRL', blank=True, null=True)  # Field name made lowercase.
    hsic = models.FloatField(db_column='HSIC', blank=True, null=True)  # Field name made lowercase.
    hst = models.FloatField(db_column='HST', blank=True, null=True)  # Field name made lowercase.
    hsy = models.FloatField(db_column='HSY', blank=True, null=True)  # Field name made lowercase.
    hum = models.FloatField(db_column='HUM', blank=True, null=True)  # Field name made lowercase.
    hwm = models.FloatField(db_column='HWM', blank=True, null=True)  # Field name made lowercase.
    ibm = models.FloatField(db_column='IBM', blank=True, null=True)  # Field name made lowercase.
    ice = models.FloatField(db_column='ICE', blank=True, null=True)  # Field name made lowercase.
    idxx = models.FloatField(db_column='IDXX', blank=True, null=True)  # Field name made lowercase.
    iex = models.FloatField(db_column='IEX', blank=True, null=True)  # Field name made lowercase.
    iff = models.FloatField(db_column='IFF', blank=True, null=True)  # Field name made lowercase.
    ilmn = models.FloatField(db_column='ILMN', blank=True, null=True)  # Field name made lowercase.
    incy = models.FloatField(db_column='INCY', blank=True, null=True)  # Field name made lowercase.
    info = models.FloatField(db_column='INFO', blank=True, null=True)  # Field name made lowercase.
    intc = models.FloatField(db_column='INTC', blank=True, null=True)  # Field name made lowercase.
    intu = models.FloatField(db_column='INTU', blank=True, null=True)  # Field name made lowercase.
    ip = models.FloatField(db_column='IP', blank=True, null=True)  # Field name made lowercase.
    ipg = models.FloatField(db_column='IPG', blank=True, null=True)  # Field name made lowercase.
    ipgp = models.FloatField(db_column='IPGP', blank=True, null=True)  # Field name made lowercase.
    iqv = models.FloatField(db_column='IQV', blank=True, null=True)  # Field name made lowercase.
    ir = models.FloatField(db_column='IR', blank=True, null=True)  # Field name made lowercase.
    irm = models.FloatField(db_column='IRM', blank=True, null=True)  # Field name made lowercase.
    isrg = models.FloatField(db_column='ISRG', blank=True, null=True)  # Field name made lowercase.
    it = models.FloatField(db_column='IT', blank=True, null=True)  # Field name made lowercase.
    itw = models.FloatField(db_column='ITW', blank=True, null=True)  # Field name made lowercase.
    ivz = models.FloatField(db_column='IVZ', blank=True, null=True)  # Field name made lowercase.
    j = models.FloatField(db_column='J', blank=True, null=True)  # Field name made lowercase.
    jbht = models.FloatField(db_column='JBHT', blank=True, null=True)  # Field name made lowercase.
    jci = models.FloatField(db_column='JCI', blank=True, null=True)  # Field name made lowercase.
    jkhy = models.FloatField(db_column='JKHY', blank=True, null=True)  # Field name made lowercase.
    jnj = models.FloatField(db_column='JNJ', blank=True, null=True)  # Field name made lowercase.
    jnpr = models.FloatField(db_column='JNPR', blank=True, null=True)  # Field name made lowercase.
    jpm = models.FloatField(db_column='JPM', blank=True, null=True)  # Field name made lowercase.
    k = models.FloatField(db_column='K', blank=True, null=True)  # Field name made lowercase.
    key = models.FloatField(db_column='KEY', blank=True, null=True)  # Field name made lowercase.
    keys = models.FloatField(db_column='KEYS', blank=True, null=True)  # Field name made lowercase.
    khc = models.FloatField(db_column='KHC', blank=True, null=True)  # Field name made lowercase.
    kim = models.FloatField(db_column='KIM', blank=True, null=True)  # Field name made lowercase.
    klac = models.FloatField(db_column='KLAC', blank=True, null=True)  # Field name made lowercase.
    kmb = models.FloatField(db_column='KMB', blank=True, null=True)  # Field name made lowercase.
    kmi = models.FloatField(db_column='KMI', blank=True, null=True)  # Field name made lowercase.
    kmx = models.FloatField(db_column='KMX', blank=True, null=True)  # Field name made lowercase.
    ko = models.FloatField(db_column='KO', blank=True, null=True)  # Field name made lowercase.
    kr = models.FloatField(db_column='KR', blank=True, null=True)  # Field name made lowercase.
    ksu = models.FloatField(db_column='KSU', blank=True, null=True)  # Field name made lowercase.
    l = models.FloatField(db_column='L', blank=True, null=True)  # Field name made lowercase.
    lb = models.FloatField(db_column='LB', blank=True, null=True)  # Field name made lowercase.
    ldos = models.FloatField(db_column='LDOS', blank=True, null=True)  # Field name made lowercase.
    leg = models.FloatField(db_column='LEG', blank=True, null=True)  # Field name made lowercase.
    len = models.FloatField(db_column='LEN', blank=True, null=True)  # Field name made lowercase.
    lh = models.FloatField(db_column='LH', blank=True, null=True)  # Field name made lowercase.
    lhx = models.FloatField(db_column='LHX', blank=True, null=True)  # Field name made lowercase.
    lin = models.FloatField(db_column='LIN', blank=True, null=True)  # Field name made lowercase.
    lkq = models.FloatField(db_column='LKQ', blank=True, null=True)  # Field name made lowercase.
    lly = models.FloatField(db_column='LLY', blank=True, null=True)  # Field name made lowercase.
    lmt = models.FloatField(db_column='LMT', blank=True, null=True)  # Field name made lowercase.
    lnc = models.FloatField(db_column='LNC', blank=True, null=True)  # Field name made lowercase.
    lnt = models.FloatField(db_column='LNT', blank=True, null=True)  # Field name made lowercase.
    low = models.FloatField(db_column='LOW', blank=True, null=True)  # Field name made lowercase.
    lrcx = models.FloatField(db_column='LRCX', blank=True, null=True)  # Field name made lowercase.
    lumn = models.FloatField(db_column='LUMN', blank=True, null=True)  # Field name made lowercase.
    luv = models.FloatField(db_column='LUV', blank=True, null=True)  # Field name made lowercase.
    lvs = models.FloatField(db_column='LVS', blank=True, null=True)  # Field name made lowercase.
    lw = models.FloatField(db_column='LW', blank=True, null=True)  # Field name made lowercase.
    lyb = models.FloatField(db_column='LYB', blank=True, null=True)  # Field name made lowercase.
    lyv = models.FloatField(db_column='LYV', blank=True, null=True)  # Field name made lowercase.
    ma = models.FloatField(db_column='MA', blank=True, null=True)  # Field name made lowercase.
    maa = models.FloatField(db_column='MAA', blank=True, null=True)  # Field name made lowercase.
    mar = models.FloatField(db_column='MAR', blank=True, null=True)  # Field name made lowercase.
    mas = models.FloatField(db_column='MAS', blank=True, null=True)  # Field name made lowercase.
    mcd = models.FloatField(db_column='MCD', blank=True, null=True)  # Field name made lowercase.
    mchp = models.FloatField(db_column='MCHP', blank=True, null=True)  # Field name made lowercase.
    mck = models.FloatField(db_column='MCK', blank=True, null=True)  # Field name made lowercase.
    mco = models.FloatField(db_column='MCO', blank=True, null=True)  # Field name made lowercase.
    mdlz = models.FloatField(db_column='MDLZ', blank=True, null=True)  # Field name made lowercase.
    mdt = models.FloatField(db_column='MDT', blank=True, null=True)  # Field name made lowercase.
    met = models.FloatField(db_column='MET', blank=True, null=True)  # Field name made lowercase.
    mgm = models.FloatField(db_column='MGM', blank=True, null=True)  # Field name made lowercase.
    mhk = models.FloatField(db_column='MHK', blank=True, null=True)  # Field name made lowercase.
    mkc = models.FloatField(db_column='MKC', blank=True, null=True)  # Field name made lowercase.
    mktx = models.FloatField(db_column='MKTX', blank=True, null=True)  # Field name made lowercase.
    mlm = models.FloatField(db_column='MLM', blank=True, null=True)  # Field name made lowercase.
    mmc = models.FloatField(db_column='MMC', blank=True, null=True)  # Field name made lowercase.
    mmm = models.FloatField(db_column='MMM', blank=True, null=True)  # Field name made lowercase.
    mnst = models.FloatField(db_column='MNST', blank=True, null=True)  # Field name made lowercase.
    mo = models.FloatField(db_column='MO', blank=True, null=True)  # Field name made lowercase.
    mos = models.FloatField(db_column='MOS', blank=True, null=True)  # Field name made lowercase.
    mpc = models.FloatField(db_column='MPC', blank=True, null=True)  # Field name made lowercase.
    mpwr = models.FloatField(db_column='MPWR', blank=True, null=True)  # Field name made lowercase.
    mrk = models.FloatField(db_column='MRK', blank=True, null=True)  # Field name made lowercase.
    mro = models.FloatField(db_column='MRO', blank=True, null=True)  # Field name made lowercase.
    ms = models.FloatField(db_column='MS', blank=True, null=True)  # Field name made lowercase.
    msci = models.FloatField(db_column='MSCI', blank=True, null=True)  # Field name made lowercase.
    msft = models.FloatField(db_column='MSFT', blank=True, null=True)  # Field name made lowercase.
    msi = models.FloatField(db_column='MSI', blank=True, null=True)  # Field name made lowercase.
    mtb = models.FloatField(db_column='MTB', blank=True, null=True)  # Field name made lowercase.
    mtd = models.FloatField(db_column='MTD', blank=True, null=True)  # Field name made lowercase.
    mu = models.FloatField(db_column='MU', blank=True, null=True)  # Field name made lowercase.
    mxim = models.FloatField(db_column='MXIM', blank=True, null=True)  # Field name made lowercase.
    nclh = models.FloatField(db_column='NCLH', blank=True, null=True)  # Field name made lowercase.
    ndaq = models.FloatField(db_column='NDAQ', blank=True, null=True)  # Field name made lowercase.
    nee = models.FloatField(db_column='NEE', blank=True, null=True)  # Field name made lowercase.
    nem = models.FloatField(db_column='NEM', blank=True, null=True)  # Field name made lowercase.
    nflx = models.FloatField(db_column='NFLX', blank=True, null=True)  # Field name made lowercase.
    ni = models.FloatField(db_column='NI', blank=True, null=True)  # Field name made lowercase.
    nke = models.FloatField(db_column='NKE', blank=True, null=True)  # Field name made lowercase.
    nlok = models.FloatField(db_column='NLOK', blank=True, null=True)  # Field name made lowercase.
    nlsn = models.FloatField(db_column='NLSN', blank=True, null=True)  # Field name made lowercase.
    noc = models.FloatField(db_column='NOC', blank=True, null=True)  # Field name made lowercase.
    nov = models.FloatField(db_column='NOV', blank=True, null=True)  # Field name made lowercase.
    now = models.FloatField(db_column='NOW', blank=True, null=True)  # Field name made lowercase.
    nrg = models.FloatField(db_column='NRG', blank=True, null=True)  # Field name made lowercase.
    nsc = models.FloatField(db_column='NSC', blank=True, null=True)  # Field name made lowercase.
    ntap = models.FloatField(db_column='NTAP', blank=True, null=True)  # Field name made lowercase.
    ntrs = models.FloatField(db_column='NTRS', blank=True, null=True)  # Field name made lowercase.
    nue = models.FloatField(db_column='NUE', blank=True, null=True)  # Field name made lowercase.
    nvda = models.FloatField(db_column='NVDA', blank=True, null=True)  # Field name made lowercase.
    nvr = models.FloatField(db_column='NVR', blank=True, null=True)  # Field name made lowercase.
    nwl = models.FloatField(db_column='NWL', blank=True, null=True)  # Field name made lowercase.
    nws = models.FloatField(db_column='NWS', blank=True, null=True)  # Field name made lowercase.
    nwsa = models.FloatField(db_column='NWSA', blank=True, null=True)  # Field name made lowercase.
    nxpi = models.FloatField(db_column='NXPI', blank=True, null=True)  # Field name made lowercase.
    o = models.FloatField(db_column='O', blank=True, null=True)  # Field name made lowercase.
    odfl = models.FloatField(db_column='ODFL', blank=True, null=True)  # Field name made lowercase.
    oke = models.FloatField(db_column='OKE', blank=True, null=True)  # Field name made lowercase.
    omc = models.FloatField(db_column='OMC', blank=True, null=True)  # Field name made lowercase.
    orcl = models.FloatField(db_column='ORCL', blank=True, null=True)  # Field name made lowercase.
    orly = models.FloatField(db_column='ORLY', blank=True, null=True)  # Field name made lowercase.
    otis = models.FloatField(db_column='OTIS', blank=True, null=True)  # Field name made lowercase.
    oxy = models.FloatField(db_column='OXY', blank=True, null=True)  # Field name made lowercase.
    payc = models.FloatField(db_column='PAYC', blank=True, null=True)  # Field name made lowercase.
    payx = models.FloatField(db_column='PAYX', blank=True, null=True)  # Field name made lowercase.
    pbct = models.FloatField(db_column='PBCT', blank=True, null=True)  # Field name made lowercase.
    pcar = models.FloatField(db_column='PCAR', blank=True, null=True)  # Field name made lowercase.
    peak = models.FloatField(db_column='PEAK', blank=True, null=True)  # Field name made lowercase.
    peg = models.FloatField(db_column='PEG', blank=True, null=True)  # Field name made lowercase.
    penn = models.FloatField(db_column='PENN', blank=True, null=True)  # Field name made lowercase.
    pep = models.FloatField(db_column='PEP', blank=True, null=True)  # Field name made lowercase.
    pfe = models.FloatField(db_column='PFE', blank=True, null=True)  # Field name made lowercase.
    pfg = models.FloatField(db_column='PFG', blank=True, null=True)  # Field name made lowercase.
    pg = models.FloatField(db_column='PG', blank=True, null=True)  # Field name made lowercase.
    pgr = models.FloatField(db_column='PGR', blank=True, null=True)  # Field name made lowercase.
    ph = models.FloatField(db_column='PH', blank=True, null=True)  # Field name made lowercase.
    phm = models.FloatField(db_column='PHM', blank=True, null=True)  # Field name made lowercase.
    pkg = models.FloatField(db_column='PKG', blank=True, null=True)  # Field name made lowercase.
    pki = models.FloatField(db_column='PKI', blank=True, null=True)  # Field name made lowercase.
    pld = models.FloatField(db_column='PLD', blank=True, null=True)  # Field name made lowercase.
    pm = models.FloatField(db_column='PM', blank=True, null=True)  # Field name made lowercase.
    pnc = models.FloatField(db_column='PNC', blank=True, null=True)  # Field name made lowercase.
    pnr = models.FloatField(db_column='PNR', blank=True, null=True)  # Field name made lowercase.
    pnw = models.FloatField(db_column='PNW', blank=True, null=True)  # Field name made lowercase.
    pool = models.FloatField(db_column='POOL', blank=True, null=True)  # Field name made lowercase.
    ppg = models.FloatField(db_column='PPG', blank=True, null=True)  # Field name made lowercase.
    ppl = models.FloatField(db_column='PPL', blank=True, null=True)  # Field name made lowercase.
    prgo = models.FloatField(db_column='PRGO', blank=True, null=True)  # Field name made lowercase.
    pru = models.FloatField(db_column='PRU', blank=True, null=True)  # Field name made lowercase.
    psa = models.FloatField(db_column='PSA', blank=True, null=True)  # Field name made lowercase.
    psx = models.FloatField(db_column='PSX', blank=True, null=True)  # Field name made lowercase.
    ptc = models.FloatField(db_column='PTC', blank=True, null=True)  # Field name made lowercase.
    pvh = models.FloatField(db_column='PVH', blank=True, null=True)  # Field name made lowercase.
    pwr = models.FloatField(db_column='PWR', blank=True, null=True)  # Field name made lowercase.
    pxd = models.FloatField(db_column='PXD', blank=True, null=True)  # Field name made lowercase.
    pypl = models.FloatField(db_column='PYPL', blank=True, null=True)  # Field name made lowercase.
    qcom = models.FloatField(db_column='QCOM', blank=True, null=True)  # Field name made lowercase.
    qrvo = models.FloatField(db_column='QRVO', blank=True, null=True)  # Field name made lowercase.
    rcl = models.FloatField(db_column='RCL', blank=True, null=True)  # Field name made lowercase.
    re = models.FloatField(db_column='RE', blank=True, null=True)  # Field name made lowercase.
    reg = models.FloatField(db_column='REG', blank=True, null=True)  # Field name made lowercase.
    regn = models.FloatField(db_column='REGN', blank=True, null=True)  # Field name made lowercase.
    rf = models.FloatField(db_column='RF', blank=True, null=True)  # Field name made lowercase.
    rhi = models.FloatField(db_column='RHI', blank=True, null=True)  # Field name made lowercase.
    rjf = models.FloatField(db_column='RJF', blank=True, null=True)  # Field name made lowercase.
    rl = models.FloatField(db_column='RL', blank=True, null=True)  # Field name made lowercase.
    rmd = models.FloatField(db_column='RMD', blank=True, null=True)  # Field name made lowercase.
    rok = models.FloatField(db_column='ROK', blank=True, null=True)  # Field name made lowercase.
    rol = models.FloatField(db_column='ROL', blank=True, null=True)  # Field name made lowercase.
    rop = models.FloatField(db_column='ROP', blank=True, null=True)  # Field name made lowercase.
    rost = models.FloatField(db_column='ROST', blank=True, null=True)  # Field name made lowercase.
    rsg = models.FloatField(db_column='RSG', blank=True, null=True)  # Field name made lowercase.
    rtx = models.FloatField(db_column='RTX', blank=True, null=True)  # Field name made lowercase.
    sbac = models.FloatField(db_column='SBAC', blank=True, null=True)  # Field name made lowercase.
    sbux = models.FloatField(db_column='SBUX', blank=True, null=True)  # Field name made lowercase.
    schw = models.FloatField(db_column='SCHW', blank=True, null=True)  # Field name made lowercase.
    see = models.FloatField(db_column='SEE', blank=True, null=True)  # Field name made lowercase.
    shw = models.FloatField(db_column='SHW', blank=True, null=True)  # Field name made lowercase.
    sivb = models.FloatField(db_column='SIVB', blank=True, null=True)  # Field name made lowercase.
    sjm = models.FloatField(db_column='SJM', blank=True, null=True)  # Field name made lowercase.
    slb = models.FloatField(db_column='SLB', blank=True, null=True)  # Field name made lowercase.
    sna = models.FloatField(db_column='SNA', blank=True, null=True)  # Field name made lowercase.
    snps = models.FloatField(db_column='SNPS', blank=True, null=True)  # Field name made lowercase.
    so = models.FloatField(db_column='SO', blank=True, null=True)  # Field name made lowercase.
    spg = models.FloatField(db_column='SPG', blank=True, null=True)  # Field name made lowercase.
    spgi = models.FloatField(db_column='SPGI', blank=True, null=True)  # Field name made lowercase.
    sre = models.FloatField(db_column='SRE', blank=True, null=True)  # Field name made lowercase.
    ste = models.FloatField(db_column='STE', blank=True, null=True)  # Field name made lowercase.
    stt = models.FloatField(db_column='STT', blank=True, null=True)  # Field name made lowercase.
    stx = models.FloatField(db_column='STX', blank=True, null=True)  # Field name made lowercase.
    stz = models.FloatField(db_column='STZ', blank=True, null=True)  # Field name made lowercase.
    swk = models.FloatField(db_column='SWK', blank=True, null=True)  # Field name made lowercase.
    swks = models.FloatField(db_column='SWKS', blank=True, null=True)  # Field name made lowercase.
    syf = models.FloatField(db_column='SYF', blank=True, null=True)  # Field name made lowercase.
    syk = models.FloatField(db_column='SYK', blank=True, null=True)  # Field name made lowercase.
    syy = models.FloatField(db_column='SYY', blank=True, null=True)  # Field name made lowercase.
    t = models.FloatField(db_column='T', blank=True, null=True)  # Field name made lowercase.
    tap = models.FloatField(db_column='TAP', blank=True, null=True)  # Field name made lowercase.
    tdg = models.FloatField(db_column='TDG', blank=True, null=True)  # Field name made lowercase.
    tdy = models.FloatField(db_column='TDY', blank=True, null=True)  # Field name made lowercase.
    tel = models.FloatField(db_column='TEL', blank=True, null=True)  # Field name made lowercase.
    ter = models.FloatField(db_column='TER', blank=True, null=True)  # Field name made lowercase.
    tfc = models.FloatField(db_column='TFC', blank=True, null=True)  # Field name made lowercase.
    tfx = models.FloatField(db_column='TFX', blank=True, null=True)  # Field name made lowercase.
    tgt = models.FloatField(db_column='TGT', blank=True, null=True)  # Field name made lowercase.
    tjx = models.FloatField(db_column='TJX', blank=True, null=True)  # Field name made lowercase.
    tmo = models.FloatField(db_column='TMO', blank=True, null=True)  # Field name made lowercase.
    tmus = models.FloatField(db_column='TMUS', blank=True, null=True)  # Field name made lowercase.
    tpr = models.FloatField(db_column='TPR', blank=True, null=True)  # Field name made lowercase.
    trmb = models.FloatField(db_column='TRMB', blank=True, null=True)  # Field name made lowercase.
    trow = models.FloatField(db_column='TROW', blank=True, null=True)  # Field name made lowercase.
    trv = models.FloatField(db_column='TRV', blank=True, null=True)  # Field name made lowercase.
    tsco = models.FloatField(db_column='TSCO', blank=True, null=True)  # Field name made lowercase.
    tsla = models.FloatField(db_column='TSLA', blank=True, null=True)  # Field name made lowercase.
    tsn = models.FloatField(db_column='TSN', blank=True, null=True)  # Field name made lowercase.
    tt = models.FloatField(db_column='TT', blank=True, null=True)  # Field name made lowercase.
    ttwo = models.FloatField(db_column='TTWO', blank=True, null=True)  # Field name made lowercase.
    twtr = models.FloatField(db_column='TWTR', blank=True, null=True)  # Field name made lowercase.
    txn = models.FloatField(db_column='TXN', blank=True, null=True)  # Field name made lowercase.
    txt = models.FloatField(db_column='TXT', blank=True, null=True)  # Field name made lowercase.
    tyl = models.FloatField(db_column='TYL', blank=True, null=True)  # Field name made lowercase.
    ua = models.FloatField(db_column='UA', blank=True, null=True)  # Field name made lowercase.
    uaa = models.FloatField(db_column='UAA', blank=True, null=True)  # Field name made lowercase.
    ual = models.FloatField(db_column='UAL', blank=True, null=True)  # Field name made lowercase.
    udr = models.FloatField(db_column='UDR', blank=True, null=True)  # Field name made lowercase.
    uhs = models.FloatField(db_column='UHS', blank=True, null=True)  # Field name made lowercase.
    ulta = models.FloatField(db_column='ULTA', blank=True, null=True)  # Field name made lowercase.
    unh = models.FloatField(db_column='UNH', blank=True, null=True)  # Field name made lowercase.
    unm = models.FloatField(db_column='UNM', blank=True, null=True)  # Field name made lowercase.
    unp = models.FloatField(db_column='UNP', blank=True, null=True)  # Field name made lowercase.
    ups = models.FloatField(db_column='UPS', blank=True, null=True)  # Field name made lowercase.
    uri = models.FloatField(db_column='URI', blank=True, null=True)  # Field name made lowercase.
    usb = models.FloatField(db_column='USB', blank=True, null=True)  # Field name made lowercase.
    v = models.FloatField(db_column='V', blank=True, null=True)  # Field name made lowercase.
    vfc = models.FloatField(db_column='VFC', blank=True, null=True)  # Field name made lowercase.
    viac = models.FloatField(db_column='VIAC', blank=True, null=True)  # Field name made lowercase.
    vlo = models.FloatField(db_column='VLO', blank=True, null=True)  # Field name made lowercase.
    vmc = models.FloatField(db_column='VMC', blank=True, null=True)  # Field name made lowercase.
    vno = models.FloatField(db_column='VNO', blank=True, null=True)  # Field name made lowercase.
    vrsk = models.FloatField(db_column='VRSK', blank=True, null=True)  # Field name made lowercase.
    vrsn = models.FloatField(db_column='VRSN', blank=True, null=True)  # Field name made lowercase.
    vrtx = models.FloatField(db_column='VRTX', blank=True, null=True)  # Field name made lowercase.
    vtr = models.FloatField(db_column='VTR', blank=True, null=True)  # Field name made lowercase.
    vtrs = models.FloatField(db_column='VTRS', blank=True, null=True)  # Field name made lowercase.
    vz = models.FloatField(db_column='VZ', blank=True, null=True)  # Field name made lowercase.
    wab = models.FloatField(db_column='WAB', blank=True, null=True)  # Field name made lowercase.
    wat = models.FloatField(db_column='WAT', blank=True, null=True)  # Field name made lowercase.
    wba = models.FloatField(db_column='WBA', blank=True, null=True)  # Field name made lowercase.
    wdc = models.FloatField(db_column='WDC', blank=True, null=True)  # Field name made lowercase.
    wec = models.FloatField(db_column='WEC', blank=True, null=True)  # Field name made lowercase.
    well = models.FloatField(db_column='WELL', blank=True, null=True)  # Field name made lowercase.
    wfc = models.FloatField(db_column='WFC', blank=True, null=True)  # Field name made lowercase.
    whr = models.FloatField(db_column='WHR', blank=True, null=True)  # Field name made lowercase.
    wltw = models.FloatField(db_column='WLTW', blank=True, null=True)  # Field name made lowercase.
    wm = models.FloatField(db_column='WM', blank=True, null=True)  # Field name made lowercase.
    wmb = models.FloatField(db_column='WMB', blank=True, null=True)  # Field name made lowercase.
    wmt = models.FloatField(db_column='WMT', blank=True, null=True)  # Field name made lowercase.
    wrb = models.FloatField(db_column='WRB', blank=True, null=True)  # Field name made lowercase.
    wrk = models.FloatField(db_column='WRK', blank=True, null=True)  # Field name made lowercase.
    wst = models.FloatField(db_column='WST', blank=True, null=True)  # Field name made lowercase.
    wu = models.FloatField(db_column='WU', blank=True, null=True)  # Field name made lowercase.
    wy = models.FloatField(db_column='WY', blank=True, null=True)  # Field name made lowercase.
    wynn = models.FloatField(db_column='WYNN', blank=True, null=True)  # Field name made lowercase.
    xel = models.FloatField(db_column='XEL', blank=True, null=True)  # Field name made lowercase.
    xlnx = models.FloatField(db_column='XLNX', blank=True, null=True)  # Field name made lowercase.
    xom = models.FloatField(db_column='XOM', blank=True, null=True)  # Field name made lowercase.
    xray = models.FloatField(db_column='XRAY', blank=True, null=True)  # Field name made lowercase.
    xyl = models.FloatField(db_column='XYL', blank=True, null=True)  # Field name made lowercase.
    yum = models.FloatField(db_column='YUM', blank=True, null=True)  # Field name made lowercase.
    zbh = models.FloatField(db_column='ZBH', blank=True, null=True)  # Field name made lowercase.
    zbra = models.FloatField(db_column='ZBRA', blank=True, null=True)  # Field name made lowercase.
    zion = models.FloatField(db_column='ZION', blank=True, null=True)  # Field name made lowercase.
    zts = models.FloatField(db_column='ZTS', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'stock_price'
